# Copyright (c) 2018-2025 Richard Huang <rickypc@users.noreply.github.com>
# Description: Setup composite GHA.
# File: action.yml
# License: AGPL-3.0-or-later

description: Checkout, setup Node.js, and install dependencies
name: Setup
inputs:
  cache-dependency-path:
    default: package.json
    description: Path to dependency file for caching
    required: false
  node-version:
    description: Node.js version to use
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: yarn
        cache-dependency-path: ${{inputs.cache-dependency-path}}
        node-version: ${{inputs.node-version}}
    - name: Install
      run: yarn
      shell: bash
