[test]
coveragePathIgnorePatterns = ["**/dist/**", "**/tests/**"]
coverageReporter = ["lcov", "text"]
coverageSkipTestFiles = true
coverageThreshold = { functions = 1.0, lines = 1.0, statements = 1.0 }
preload = ["./tests/preload.ts"]
