# Copyright (c) 2018-2025 Richard Huang <rickypc@users.noreply.github.com>
# Description: Validate composite GHA.
# File: action.yml
# License: AGPL-3.0-or-later

description: Setup Node.js, install dependencies, run a validation command.
name: Setup
inputs:
  cache-dependency-path:
    default: package.json
    description: Path to dependency file for caching
    required: false
  command:
    description: Validation command to run after install
    required: true
  node-version:
    description: Node.js version to use
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache: yarn
        cache-dependency-path: ${{inputs.cache-dependency-path}}
        node-version: ${{inputs.node-version}}
    - name: Install
      run: |
        echo "::group::Install Dependencies"
        yarn
        echo "::endgroup::"
      shell: bash
    - name: Validate
      run: |
        echo "::group::Running Validation"
        ${{inputs.command}}
        echo "::endgroup::"
      shell: bash
