# Copyright © 2018 Richard Huang <rickypc@users.noreply.github.com>
# Description: Validations GHA.
# File: validations.yml
# License: AGPL-3.0-or-later

name: Validations
on:
  pull_request:
    types: [ edited, opened, reopened, synchronize ]
  push:
    branches:
      - main
jobs:
  deps:
    name: Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate
        uses: ./.github/actions/validate
        with:
          command: bun run test:deps:ci
  leak:
    name: Leak
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate
        uses: ./.github/actions/validate
        with:
          command: bun run test:leak:ci
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate
        uses: ./.github/actions/validate
        with:
          command: bun run test:lint
  perf:
    name: Perf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate
        uses: ./.github/actions/validate
        with:
          command: bun run test:perf:ci
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate
        uses: ./.github/actions/validate
        with:
          command: bun run test:type
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Validate
        uses: ./.github/actions/validate
        with:
          command: bun run test:unit:ci
      - name: Codecov
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          flags: unittests
